### PR TITLE
Infra update 

### PR DESCRIPTION
**Pull request by sean-m-sullivan**
# What does this PR do?
Updates references from redhat_cop to infra, mainly the readmes

In draft as I figure in how to unbreak the breaking change.

# How should this be tested?

# Is there a relevant Issue open for this?

resolves #[number]

# Other Relevant info, PRs, etc

### CODE REVIEW

**Review by djdanielsson — APPROVED** [review]
I am good with this if you want to do it now or wait until 2.4 when we officially drop redhat_cop namespace

**Review by silvinux — COMMENTED** [review]
LGTM! Awesome. But I think we should wait until the 2.4 is released, basically there are a lot of customers/users that might don't know about the change.

**Comment by sean-m-sullivan** [comment]
@silvinux we are looking at doing the change now so we can provide this in a release with the 2.4 bundle. So this is prepping for release.

**Comment by silvinux** [comment]
> @silvinux we are looking at doing the change now so we can provide this in a release with the 2.4 bundle. So this is prepping for release.

It's Ok, I'll try to contact them.

**Pull request merged**
