### PR TITLE
Make galaxy.yml persistent and move out ansible.cfg

### PR DESCRIPTION
**Pull request by Tompage1994**
# What does this PR do?
Makes galaxy.yml persistent and moves the template out of root. Also moves ansible.cfg from root.

This makes it installable from source

# How should this be tested?
1. Test we can install from source
2. We will need to perform a release and ensure that the galaxy.yml remains in the repo with `-devel` appended to the version that's just been released. We need to also be sure that the galaxy.yml of the released version is correct

# Is there a relevant Issue open for this?

related https://github.com/ansible/automation_hub_collection/issues/280

# Other Relevant info, PRs, etc
Required https://github.com/redhat-cop/ansible_collections_tooling/pull/33 to be merged

### CODE REVIEW

**Comment by Tompage1994** [comment]
Tests will all be failing until https://github.com/redhat-cop/ansible_collections_tooling/pull/33 is merged

**Review by djdanielsson — APPROVED** [review]
LGTM

**Review by sean-m-sullivan — APPROVED** [review]
Trying to figure out the cli test is failing, but looks good to me

**Comment by Tompage1994** [comment]
> Trying to figure out the cli test is failing, but looks good to me

@sean-m-sullivan fix here: https://github.com/redhat-cop/ansible_collections_tooling/pull/34

**Comment by sean-m-sullivan** [comment]
@Tompage1994 thought you were referring to the original tooling change, rerunning.

**Comment by Tompage1994** [comment]
Looks like that could be working now

**Comment by Tompage1994** [comment]
> Looks like that could be working now

or not...

**Comment by Tompage1994** [comment]
Looks like it may not be related to my changes then.

**Pull request merged**
