### PR TITLE
updating ansible version to supported version 2.15.0

### PR DESCRIPTION
**Pull request by djdanielsson**

### CODE REVIEW

**Comment by Tompage1994** [comment]
Do we really need to be restricting this to run only with supported versions? I get that we may not support anything broken with old ansible versions but I don't agree we should actually be stopping people from using older ansible?

**Comment by branic** [comment]
I think it is a matter of what versions the CI is testing and how many versions the maintainers want to support. Setting the minimum version is a way to say "this is the earliest version that we test".

**Comment by djdanielsson** [comment]
it doesn't stop people from using it, I think it will just give a warning that they are using a version we do not support which is what we want to be clear about

**Review by adonisgarciac — APPROVED** [review]
LGTM.

**Comment by djdanielsson** [comment]
It looks like the pipeline is failing again, Im forcing merging this

**Pull request merged**
