### PR TITLE
added 'return_all: true' at every object type

### LINKED ISSUE #440: object_diff role does not account for paginated API responses
We need to add "return_all: true" to API queries in object_diff role to ensure all objects are included in the responses.
Currently this is not the case and only the first page of results (25 objects) are returned.

### PR DESCRIPTION
**Pull request by ivarmu**
# What does this PR do?

`return_all: true` has been added to return the maximum of `max_objects=query_controller_api_max_objects` objects.

# How should this be tested?

The repository automated tests has been passed.

# Is there a relevant Issue open for this?

resolves #440 

# Other Relevant info, PRs, etc

N/A

### CODE REVIEW

**Review by Tompage1994 — CHANGES_REQUESTED** [review]
Mostly LGTM.

Can you please add a changelog fragment and also add a description of the `query_controller_api_max_objects` variable to the readme for this role?

Thanks

**Comment by ivarmu** [comment]
> Mostly LGTM.
> 
> Can you please add a changelog fragment and also add a description of the `query_controller_api_max_objects` variable to the readme for this role?
> 
> Thanks

Done! Thanks!

**Review by Tompage1994 — APPROVED** [review]
LGTM

**Review by sean-m-sullivan — APPROVED** [review]
LGTM

**Pull request merged**
