### PR TITLE
Add the Workflow Job Template Nodes into the generated Workflow Job Template yaml file

### PR DESCRIPTION
**Pull request by ivarmu**
### What does this PR do?
When exporting the workflow job templates, this PR is putting it's nodes in the `simplified_workflow_nodes` variable, so it's compatible with the `dispatch` role.

### How should this be tested?
```
$ cat filetree_create.yml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: "{{ vault_controller_hostname }}"
    controller_username: "{{ vault_controller_username }}"
    controller_password: "{{ vault_controller_password }}"
    controller_validate_certs: "{{ vault_controller_validate_certs }}"
    controller_api_plugin: "ansible.controller.controller_api"
  pre_tasks:
    - name: "Check if the required input variables are present"
      assert:
        that:
          - input_tag is defined
          - (input_tag | type_debug) == 'list'
        fail_msg: 'A variable called ''input_tag'' of type ''list'' is needed: -e ''{input_tag: [organizations, projects]}'''
        quiet: true

    - name: "Check if the required input values are correct"
      assert:
        that:
          - tag_item in valid_tags
        fail_msg: "The valid tags are the following ones: {{ valid_tags | join(', ') }}"
        quiet: true
      loop: "{{ input_tag }}"
      loop_control:
        loop_var: tag_item
  roles:
    - redhat_cop.controller_configuration.filetree_create
...
$ ansible-playbook filetree_create.yml -e '{input_tag: [workflow_job_templates], output_path: ~/iam/filetree_create.2.1.7 }'
```

### Is there a relevant Issue open for this?
No issue has been opened for this.

### Other Relevant info, PRs, etc.
N/A

### CODE REVIEW

**Review by sean-m-sullivan — APPROVED** [review]
LGTM

**Review by sean-m-sullivan — CHANGES_REQUESTED** [review]
This has a merge conflict, and I am not sure what is right, can you look into this and fix it? or tell us what should stay/go?

**Comment by sean-m-sullivan** [comment]
The file in question is the 
current_workflow_job_templates.j2
and its about the Name/description stuff, as should it be 
  - name: "{{ current_workflow_job_templates_asset_value.name }}"
Current change
vs
  - name: "{{ workflow_job_template.name }}"
Incoming change

**Comment by ivarmu** [comment]
Hi @sean-m-sullivan. I've rebased that PR on the last devel version and I'm going to run tests and get back to you. I've seen that in the current `devel` branch, there are some unresolved conflicts as well, and I've fixed them as well:
```
 👒 ivan@iamlabp1 -  ✝  controller_configuration/roles/filetree_create   export_unified_wfjt_and_wfjtn  grep -R "<<<<<<< HEAD" 
tasks/user_roles.yml:<<<<<<< HEAD
tasks/team_roles.yml:<<<<<<< HEAD
tasks/teams.yml:<<<<<<< HEAD
tasks/execution_environments.yml:<<<<<<< HEAD
tasks/organizations.yml:<<<<<<< HEAD
tasks/job_templates.yml:<<<<<<< HEAD
tasks/credentials.yml:<<<<<<< HEAD
tasks/users.yml:<<<<<<< HEAD
tasks/credential_types.yml:<<<<<<< HEAD
tasks/notification_templates.yml:<<<<<<< HEAD
tasks/workflow_job_template_nodes.yml:<<<<<<< HEAD
tasks/workflow_job_template_nodes.yml:<<<<<<< HEAD
tasks/inventory.yml:<<<<<<< HEAD
tasks/projects.yml:<<<<<<< HEAD
```

Let me run this branch to check everything is OK.

**Review by sean-m-sullivan — APPROVED** [review]
LGTM, but there are merge conflicts generated by fixing the merge conflicts, will review this later to get it merged correctly

**Comment by ivarmu** [comment]
@sean-m-sullivan I've fixed the conflicts and run the branch successfully on a production environment.

**Pull request merged**
