### PR TITLE
Rename notifications to notification_templates

### LINKED ISSUE #95: Update tower_notification to tower_notification_template
The AWX collection has changed the name of `tower_notification` to `tower_notification_template`.

The same change should be made in this repo. (`notifications` role should become `notification_templates` role)

### PR DESCRIPTION
**Pull request by Tompage1994**
### What does this PR do?
Renamed notifications role to notification_templates role as in awx.awx:15.0. The variable is not tower_notification_templates.

### How should this be tested?
Automated testing

### Is there a relevant Issue open for this?
resolves #95

### Other Relevant info, PRs, etc.
#94 flagged up the need for this change.

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
lgtm

**Review by sean-m-sullivan — APPROVED** [review]
lgtm

**Comment by sean-m-sullivan** [comment]
@Tompage1994 we should have done yours first then mine, didn't expect you to approve it, and been trying to get this to "check" forever, if you can pull in the new devel to yours and "rebase" and incorporate the default changes, that should fix it, I tried to fix the merge conflicts but I can't merge my own changes.

**Comment by Tompage1994** [comment]
> @Tompage1994 we should have done yours first then mine, didn't expect you to approve it, and been trying to get this to "check" forever, if you can pull in the new devel to yours and "rebase" and incorporate the default changes, that should fix it, I tried to fix the merge conflicts but I can't merge my own changes.

Should be good to go now

**Review by sean-m-sullivan — APPROVED** [review]

**Pull request merged**
