### PR TITLE
filetree_create now allows to export objects for the specified organization

### LINKED ISSUE #610: filetree_create should export only the objects of a given organization
### Discussed in https://github.com/redhat-cop/controller_configuration/discussions/609

<div type='discussions-op-text'>

<sup>Originally posted by **ivarmu** June  7, 2023</sup>
`filetree_create` role is currently exporting all the objects from Tower/Controller.

It's needed to let the export of only one (or more) named organizations.</div>

### PR DESCRIPTION
**Pull request by ivarmu**
# What does this PR do?
Adds the possibility of exporting only the objects related to the specified organization.

# How should this be tested?
Manually tested. Automatic tests.

# Is there a relevant Issue open for this?

resolves #610 

# Other Relevant info, PRs, etc
N/A

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
These seems like a backwards way of doing it, maybe setting the query with the id?
```
        export_results: "{{ query('awx.awx.controller_api', 'inventory_sources',
                                        query_params={'order_by': 'organization,id', 'organization': '1' },
                                        host='controller.nas', username='admin', password='secret123', verify_ssl=controller_validate_certs,
                                        return_all=true)
                                }}"
```

**Comment by ivarmu** [comment]
> These seems like a backwards way of doing it, maybe setting the query with the id?
> 
> ```
>         export_results: "{{ query('awx.awx.controller_api', 'inventory_sources',
>                                         query_params={'order_by': 'organization,id', 'organization': '1' },
>                                         host='controller.nas', username='admin', password='secret123', verify_ssl=controller_validate_certs,
>                                         return_all=true)
>                                 }}"
> ```

This doesn't apply to all kinds of objects. I agree there are many objects that could be filtered directly where you propose, but some other objects requires extra queries to get the organization information... that is the reason I coded like this at a first instance.

**Comment by ivarmu** [comment]
> These seems like a backwards way of doing it, maybe setting the query with the id?
> 
> ```
>         export_results: "{{ query('awx.awx.controller_api', 'inventory_sources',
>                                         query_params={'order_by': 'organization,id', 'organization': '1' },
>                                         host='controller.nas', username='admin', password='secret123', verify_ssl=controller_validate_certs,
>                                         return_all=true)
>                                 }}"
> ```

Changed the filtering strategy. Thanks @sean-m-sullivan !!!
Users can't be search by organization through the API :-1: , so I've left them intact

**Review by sean-m-sullivan — APPROVED** [review]
I like this a lot better, alot more veratile.

**Pull request merged**
