### PR TITLE
Tower Export Organizations

### PR DESCRIPTION
**Pull request by sean-m-sullivan**
### What does this PR do?
Update to use tower export model for organizations

### How should this be tested?
Automated tests

### Is there a relevant Issue open for this?
Part of #41 Dual Data Models

### Other Relevant info, PRs, etc.
Requires PR to update simiplified playbooks.
#56

### CODE REVIEW

**Review by Tompage1994 — APPROVED** [review]
Looks good to me

**Comment by sean-m-sullivan** [comment]
Rebasing this to be cleaner prior to merge

**Comment by kedark3** [comment]
Still seeing some more conflicts. Looks good otherwise.

**Comment by sean-m-sullivan** [comment]
@kedark3 updated to remove conflicts

**Pull request merged**
