### PR TITLE
changing no_log: true for inventories to standard var

### PR DESCRIPTION
**Pull request by djdanielsson**
### What does this PR do?
changing no_log: true for inventories to standard var

### How should this be tested?
Automated

### Is there a relevant Issue open for this?
none

### Other Relevant info, PRs, etc.
none

### CODE REVIEW

**Review by Tompage1994 — CHANGES_REQUESTED** [review]
nitpick: Could you add a changelog to this as it is a legitimate bug and should be documented

**Review by sean-m-sullivan — APPROVED** [review]
Good catch

**Comment by djdanielsson** [comment]
> nitpick: Could you add a changelog to this as it is a legitimate bug and should be documented

ok, I tried to add it to changelog. Let me know if I didn't do it correctly.

**Review by Tompage1994 — APPROVED** [review]
Perfect, thanks

**Pull request merged**
