### PR TITLE
Object diff variable verifyssl and some fixes

### PR DESCRIPTION
**Pull request by adonisgarciac**
### What does this PR do?

1.- Add verify_ssl as a variable in object_diff role
2.- Remove auth info in the filetree_read role because this role itself will not connect to controller/tower
3.- Add auth example variables in playbooks which use filetree_read and dispatch roles.
4.- Fixes in some templates of filetree_create role

### How should this be tested?

Launch test playbooks for filetree_create, filetree_read and object_diff roles.

### Is there a relevant Issue open for this?

N/A

### CODE REVIEW

**Review by ivarmu — APPROVED** [review]
LGTM

**Review by Tompage1994 — APPROVED** [review]
LGTM

**Comment by Tompage1994** [comment]
Looks like there are some conflicts that need to be fixed.

**Review by silvinux — COMMENTED** [review]
LGTM

**Pull request merged**
