### PR TITLE
FQDN prep, additional workflow, other issues fixed

### PR DESCRIPTION
**Pull request by sean-m-sullivan**
### What does this PR do?
Fixes several issues, brings everything up to date with awx.awx. 
Updated workflow role to have better documentation in the defaults
Updated parts for meta/main that allows for removal of fqdn to allow for Either awx.awx or ansible.tower to be used for the roles, however there is a failure for ansible lint to qualify modules that aren't referenced by fqdn inside of roles. 

The big change is the addition of some new runners and a new workflow using them.
two runners have been added one for awx, one for tower. 
These runners are hosted on a private Openshift install and are able to deploy awx/tower to openshift and do testing, hopefully decreasing the amount of failures that we have in the workflows, and ensuring compatibility with BOTH awx/tower now. 

The testing_playbooks_awx.yml workflow is this change for now, From what I have read it will fail initially because new PRs/workflows cannot access the project secrets for security reasons, while that workflow works 100% in my branch, believe it should and we will diagnose with this test balloon. 

### How should this be tested?
This should use the workflow actions already in place and test accordingly. 

### Is there a relevant Issue open for this?
#115 Partially - this has the prework for this, but ansible-lint fails due to an issue mentioned in that issue. 
#121 / #87 All defaults are described for the workflow role and checked other roles another once over. 
#124 Added missing options, updated docs and other parts in roles.

### CODE REVIEW

**Review by Tompage1994 — APPROVED** [review]
Looks good. Could you set up the secrets `openshift_username` etc. so the pipelines work and then rerun?

Then happy to merge

**Comment by sean-m-sullivan** [comment]
@Tompage1994 The secrets are already setup and ready to run, but its a security thing that it doesn't run until commited at first to disallow extraction or other malicious acts from a random PR.

**Comment by Tompage1994** [comment]
Looking at the run it looks like it tried to run but failed because hasn't got openshift_username. Looking at the secrets I think it needs changing to that rather than openshift_user?

**Comment by sean-m-sullivan** [comment]
Here is the first run, and it succeeded as I thought it would, once merged, and should for any future PR.
https://github.com/redhat-cop/tower_configuration/runs/1669361783?check_suite_focus=true

**Pull request merged**
