### PR TITLE
Fix the defaults for survey, survey_spec to default omit

### PR DESCRIPTION
**Pull request by kedark3**
### What does this PR do?
WF Role was failing if the survery is not enabled or survey_spec is not passed.

### How should this be tested?
Basic testing calling WFs role should be good. As long as survey and survey_spec is not passed.

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
I've seen issues with this in the past, on other ones. It should default to false, not omit on survey enabled, will want to test this as well because of other odd behaviours with omit.

**Comment by sean-m-sullivan** [comment]
tested with 
```
    survey_enabled:                     "{{ workflow_loop_var.survey_enabled | default('false') }}"
    survey:                             "{{ workflow_loop_var.related.survey_spec | default( workflow_loop_var.survey_spec | default(omit)) }}"
```
and worked without issue,

**Review by Tompage1994 — DISMISSED** [review]
Like the addition of the new test case. This is something we should probably ensure we add when we fix/change functionality like this.

Only request is could you add a changelog fragment for this change as a bug fix. Then will be good to go

**Comment by kedark3** [comment]
@Tompage1994 sure let me check it out. I haven't been able to keeping up enough with repo to know that unfortunately.

**Comment by sean-m-sullivan** [comment]
@kedark3 Copy this file, change the filename, and change the text to describe what you did, 
https://github.com/redhat-cop/tower_configuration/blob/devel/changelogs/fragments/auth_update.yml

**Review by sean-m-sullivan — APPROVED** [review]
Looks good now.

**Pull request merged**
