### PR TITLE
Update linting configuration and fix lint errors

### PR DESCRIPTION
**Pull request by branic**
### What does this PR do?

- Updates the linter versions
- Moves configurations to the root directory
- Adds markdown linter
- Fixes all linter reported errors
- Adds `--profile=production` to ansible-lint

### How should this be tested?

Automated tests are preferred, but not always doable - especially for infrastructure. Include commands to run your new feature, and also post-run commands to validate that it worked. (please use code blocks to format code samples)

### Is there a relevant Issue open for this?

No

### Other Relevant info, PRs, etc.

This PR aligns how linting is configured on the redhat_cop.aap_utilities repo.

### CODE REVIEW

**Review by ivarmu — APPROVED** [review]
LGTM. Great job! I think it'll generate conflicts with the PR #360, so, as that one is touching a very large number of files, I think it should be better to merge it first, and afterwards rebase + merge the #360 (fixing the conflicts where needed)

@sean-m-sullivan @Tompage1994 @djdanielsson What do you think?

**Review by djdanielsson — CHANGES_REQUESTED** [review]
please fix conflicts

**Comment by silvinux** [comment]
LGTM. Great job!, just fixing conflicts and it would be good to be merged.

**Comment by branic** [comment]
Merge conflicts has been fixed.

**Review by djdanielsson — APPROVED** [review]
LGTM

**Pull request merged**
