### PR TITLE
Shorten label on some loops to show name instead of entire json block

### PR DESCRIPTION
**Pull request by MallocArray**
The current label of the step to wait for the async job templates to complete shows the full JSON output of the job var, which is very verbose and can be especially long when a survey is included.

Shorten the output so it only shows the name of the job template, very similar to the task that  manages controller job templates

# What does this PR do?

The current label of the step to wait for the async job templates to complete shows the full JSON output of the job var, which is very verbose and can be especially long when a survey is included.

Shorten the output so it only shows the name of the job template, very similar to the task that  manages controller job templates

Sample of current very verbose output from a single job template
```
TASK [infra.aap_configuration.controller_job_templates : Managing Job Templates | Wait for finish the Job Templates management] ******************************************
ok: [awx-scratch4.domain.com] => (item=Create/Update Job Template {'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': 'j689290788343.47537', 'results_file': '/root/.ansible_async/j689290788343.47537', 'changed': False, '__controller_template_item': {'name': 'Active Directory - Create CIFS Share AD Access Groups', 'description': 'Creates a computer access groups for the specified NAS Server and Share in Active Directory.', 'job_type': 'run', 'inventory': 'ActiveDirectory', 'project': 'Ansible - Development', 'playbook': 'ActiveDirectory/create_cifs_shares_access_group.yml', 'credentials': ['App Registration'], 'notification_templates_error': ['StorageTeam Notification'], 'labels': ['activedirectory', 'netapp'], 'survey_enabled': False, 'ask_variables_on_launch': True, 'roles': [{'team': 'Storage Team', 'role': 'execute'}]}, 'ansible_loop_var': '__controller_template_item'} | Wait for finish the Job Template creation)
```

After this change to only show the Job Template name

```
TASK [infra.aap_configuration.controller_job_templates : Managing Job Templates | Wait for finish the Job Templates management] ******************************************
ok: [awx-scratch4.smrcy.com] => (item=Create/Update Job Template Active Directory - Create CIFS Share AD Access Groups | Wait for finish the Job Template creation)
```
# How should this be tested?

# Is there a relevant Issue open for this?

resolves #[number]

# Other Relevant info, PRs, etc

### CODE REVIEW

**Comment by MallocArray** [comment]
There are other roles that are also showing the full JSON output as part of the label. If this shortened version is acceptable, I'm willing to open future PRs to similarly update them.

**Review by Tompage1994 — CHANGES_REQUESTED** [review]
This looks good to me. However before accepting it would be good to apply the same change to all the roles if you're happy to do so? I'd like to see that to ensure there is consistency throughout

Thanks for the contribution

**Review by djdanielsson — CHANGES_REQUESTED** [review]
Also add a changelog fragment with a summary of the change

**Comment by MallocArray** [comment]
I'm still moving into this collection and only doing the controller section.  I'm happy to update the controller roles as I run across them, and while I'll be using most of them, I'm not necessarily using all that may need updated.

I'll continue working through them and add a changelog fragment

**Comment by MallocArray** [comment]
Updated all instances that I found in my testing.
I haven't done a changelog fragment like this before, so I gave it a shot.

**Review by djdanielsson — APPROVED** [review]
LGTM

**Review by sean-m-sullivan — APPROVED** [review]

**Comment by sean-m-sullivan** [comment]
Changelog fragments can be a list of each one changed, if that makes things easier, let us know when you want to merge this, thanks for the work!

**Review by MallocArray — COMMENTED** [review]
Addressed other tasks to improve loop label

**Comment by MallocArray** [comment]
Are the fragments ok as they are now with separate files reflecting which role they relate to, or do you want only a single file with a list of the change on each role?

I'm not sure how to mark Tompage1994's requested changes as complete

**Comment by djdanielsson** [comment]
The fragments could be one file or kept as is, I think his point was just an FYI so you know that you don't have to create multiple files. @Tompage1994 needs to approve that you made the requested changes, there is nothing you can do on your side.

**Review by Tompage1994 — APPROVED** [review]

**Pull request merged**
