### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by Tompage1994**
### What does this PR do?
Fixes broken CI where a non existant EE was referenced

### How should this be tested?
CI should pass

### Is there a relevant Issue open for this?
N/A

### Other Relevant info, PRs, etc.
#334 introduced a CI failure

### CODE REVIEW

**Comment by Tompage1994** [comment]
Confirmed this does fix this issue but there is another issue with the diff section

**Comment by Tompage1994** [comment]
Think I've found the fix. No idea why the number has changed. Not sure I fully understand why it is a number (I guess ID)

**Review by djdanielsson — APPROVED** [review]
Is there a reason we use a number instead of a name?

**Comment by Tompage1994** [comment]
ok, this still doesn't work. The number seems to be different each time which means this isn't going to work. I assume this is all because the controller_api lookup returns the inventory id rather than the name. not sure what we can really do about that in this case. @sean-m-sullivan any ideas?

**Review by djdanielsson — CHANGES_REQUESTED** [review]
you should be able to use name instead of number... I think worst case we take out the diff tests and wait until it gets rewritten to add it back in

**Comment by sean-m-sullivan** [comment]
The problem is in the test itself, its getting back numbers from the API, and in the future we could look it up, or something like that, its probably best just to disable the test till we can fix it.

**Comment by Tompage1994** [comment]
Ok, I've done that. We shall see how much further it gets now

**Comment by Tompage1994** [comment]
It failed much later this time because a field has been deprecated and removed.

See https://github.com/ansible/awx/pull/12366

**Review by sean-m-sullivan — APPROVED** [review]
lGTM

**Review by djdanielsson — APPROVED** [review]
seems to be working now, sweet!

**Pull request merged**
