### PR TITLE
added no_log to the 'Populate *' tasks

### LINKED ISSUE #446: filetree_read and object_diff roles output is exposing credentials in clear text
We need to add the secure logging variables to both filetree_read and object_diff roles to avoid having credentials in clear text in console output.

### PR DESCRIPTION
**Pull request by ivarmu**
# What does this PR do?

Avoid exposing encrypted values when populating data.

# How should this be tested?

Tested manually

# Is there a relevant Issue open for this?

resolves #446 

# Other Relevant info, PRs, etc

Related PR #478

### CODE REVIEW

**Review by silvinux — APPROVED** [review]
LGTM!

**Review by Tompage1994 — CHANGES_REQUESTED** [review]
Looks good, though could you please add a changelog

**Comment by ivarmu** [comment]
> Looks good, though could you please add a changelog

I ever forget this part 😅

**Review by Tompage1994 — APPROVED** [review]
LGTM

**Pull request merged**
