### PR TITLE
fix: missing escape special characters

### LINKED ISSUE #882: Missing escaping special characters in description.
## Summary

Recently, I tried to restore job templates in our environment, but an error is showing up due to some special characters in the description.

I've managed to fix it manually in the files in two ways:

original yaml fragment:
```yaml
...
    description: "XXX report \\10.10.10.128\something$\whatever\yyy\zzz"
...

```
The first solution:
```yaml
...
    description: "XXX report \\10.10.10.128\\something\\$\\whatever\\yyy\\zzz"
...
```

The second solution:
```yaml
...
    description: 'XXX report \\10.10.10.128\something$\whatever\yyy\zzz'
...

```

But maybe you would have better solution for this. 

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

Devel affected.

## OS / ENVIRONMENT

N/A

## Desired Behavior

Export objects with proper escaped special characters

## Actual Behavior

I've ran an import script and include_vars module failed with this error:

```console (error)
"We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)
Syntax Error while loading YAML.
 found unknown escape character
The error appears to be in '/repo_dir/controller_objects/control_vars/controller_job_templates/job_scheduled.yaml':
 line 4, column 70, but maybe elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
 name: \"job_scheduled\"
 description: \"XXX \\\\10.10.10.128\\something$\\whatever\\yyy\\zzz\"\n          
}
```

## STEPS TO REPRODUCE
1) Create job template with description: `XXX report \\10.10.10.128\something$\whatever\yyy\zzz`.
2) Export Job templates with filetree_create.
3) Try to Include_vars with exported files.

Edit: double quotes present in description can break things as well.

### PR DESCRIPTION
**Pull request by przemkalit**
# What does this PR do?
fix #882 

# How should this be tested?
explained in a bug

# Is there a relevant Issue open for this?

resolves #882

# Other Relevant info, PRs, etc
N/A

### CODE REVIEW

**Review by adonisgarciac — CHANGES_REQUESTED** [review]
I'm testing this change and it is transforming:
`
XXX report \\10.10.10.128\something$\whatever\yyy\zzz
`
to 

`
XXX report \\\\\\\\10.10.10.128\\\\something\\$\\\\whatever\\\\yyy\\\\zzz
`

which ends up applying the following description:

`
XXX report \\\\10.10.10.128\\something\$\\whatever\\yyy\\zzz
`

which is not the original one.

After some tests, I think we don't need to escape $ and we should apply something like:

`
regex_replace('([\\\"])', '\\\\1')
`

which transform the description to 

`
XXX report \\\\10.10.10.128\\something$\\whatever\\yyy\\zzz
`

and it will end up applying the origin description:

`
XXX report \\10.10.10.128\something$\whatever\yyy\zzz
`

which is the original one.

**Comment by przemkalit** [comment]
Ok, I've changed the regex, thanks for the testing

**Review by adonisgarciac — CHANGES_REQUESTED** [review]
Sorry, I've tested again and it seemed to work but only for \. For " symbol it didn't work.

I think the right expression would be: 

regex_replace('([\\\"])', '\\1')

Can you test it?

**Comment by przemkalit** [comment]
> Sorry, I've tested again and it seemed to work but only for . For " symbol it didn't work.
> 
> I think the right expression would be:
> 
> regex_replace('([\"])', '\1')
> 
> Can you test it?

Sorry for late response, but this regex doesn't work and issue with loading yaml happens again.

**Comment by przemkalit** [comment]
I've reverted the regex to the proposed by me, due to my previous comment.

**Comment by przemkalit** [comment]
Hi, I've discovered that issue is related only when the files are included by the include_vars module instead of filetree_read, so I will close this PR.

**Pull request closed without merging**
