### PR TITLE
Fixes calendar icon to link to an ICS file which user can save

### PR DESCRIPTION
**Pull request by Tompage1994**
# What does this PR do?
Fixes calendar icon to link to an ICS file which user can save

# How should this be tested?
N/A
# Is there a relevant Issue open for this?
N/A

# Other Relevant info, PRs, etc
Similar to https://github.com/ansible/community/tree/main/meetings

### CODE REVIEW

**Review by djdanielsson — APPROVED** [review]
LGTM

**Review by djdanielsson — CHANGES_REQUESTED** [review]
it looks like this is failing lint/sanity checks can you see if you can fix those?

**Comment by Tompage1994** [comment]
> it looks like this is failing lint/sanity checks can you see if you can fix those?

Just pushed a 'fix' which should work. The ansible-test does NOT like the ics format

**Review by sean-m-sullivan — APPROVED** [review]
Think I fixed the final error, LGTM

**Pull request merged**
