### PR TITLE
Update required variables for controller_notification_templates

### PR DESCRIPTION
**Pull request by MallocArray**
Lines 7 and 8 of https://github.com/MallocArray/infra.aap_configuration/blob/devel/roles/controller_notification_templates/tasks/main.yml show this is a mandatory variable

# What does this PR do?

Update organization and notificaiton_type variables to be shown as required.  The current task sets them as mandatory and they are required in the AWX GUI as well

# How should this be tested?

# Is there a relevant Issue open for this?

resolves #[number]

# Other Relevant info, PRs, etc

### CODE REVIEW

**Review by djdanielsson — CHANGES_REQUESTED** [review]
This will need some further review, when looking at the module documentation, it does not show those as required and thus the code itself might need to be updated. Need to verify what is actually correct.

**Comment by MallocArray** [comment]
I had noticed that as well, since
https://docs.ansible.com/ansible/latest/collections/awx/awx/notification_template_module.html
doesn't show it as Required, but in the AWX interface, it clearly is
image

Perhaps it isn't required if `state: absent` is set, so the documentation doesn't show it as required

**Comment by djdanielsson** [comment]
I think that might be the case and thus idk if in code we want to make it required because some people might want to try and remove stuff. I am fine with updating the docs to say required but I think in the code we should remove that mandatory so remove can work.

**Comment by MallocArray** [comment]
I agree, I think it would be better to remove the Mandatory filter on them and leave the documentation as not required, which will result in matching up with the official documentation for the module and make it the most flexible.

**Comment by djdanielsson** [comment]
Feel free to make those changes if you want or I can get to it soon

**Comment by MallocArray** [comment]
Replacing with #1006

**Pull request closed without merging**
