### PR TITLE
Added exportation from api/v2/constructed_inventories endpoint.

### PR DESCRIPTION
**Pull request by ivarmu**
# What does this PR do?
- Add exportation from `api/v2/constructed_inventories` endpoint.
- Add exportation for the smart inventories.

# How should this be tested?
Manually tested. Automatic tests as well.

# Is there a relevant Issue open for this?
N/A

# Other Relevant info, PRs, etc
N/A

### CODE REVIEW

**Review by sean-m-sullivan — CHANGES_REQUESTED** [review]
looks good, need to be updated with base branch and a changelog fragment

**Review by silvinux — COMMENTED** [review]
LGTM!

**Review by djdanielsson — CHANGES_REQUESTED** [review]
if we could fix the lint errors that would be great, not sure if you just need to ignore that file or why it is even linting a .py file honestly.

**Comment by ivarmu** [comment]
> if we could fix the lint errors that would be great, not sure if you just need to ignore that file or why it is even linting a .py file honestly.

I'm fixing a lot of linter errors at #707 ... will try to rebase this one when the #707 is merged. In particular, I've added a `.ansible-lint-ignore` file to avoid these `.py` files to be ansible-linted.

**Comment by sean-m-sullivan** [comment]
With the other PR merged, can you rebase it, make sure it passes tests with the changes, otherwise looks good

**Review by sean-m-sullivan — APPROVED** [review]

**Pull request merged**
