### PR TITLE
Default cloud for kind and remove 'raw'

### PR DESCRIPTION
**Pull request by Tompage1994**
### What does this PR do?
Fixes the documentation for credential types and also adds 'cloud' as the default kind as that is what happens in the UI

### How should this be tested?
CI will run

### Is there a relevant Issue open for this?
N/A

### Other Relevant info, PRs, etc.
N/A

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
Going to need to test this, as last I checked the raw was needed for the input to come out correct.

**Comment by djdanielsson** [comment]
yes I recently tried without raw and it doesn't work

**Comment by Tompage1994** [comment]
With `"{% raw %}{  { myvar }}{% endraw %}"` the result in Tower is `"{  { myvar }}"` whereas I've found without the raw it works perfectly as required.

i.e. just setting `"{  { myvar }}"` in the variables will result in `"{{ myvar }}" in Tower.

**Comment by sean-m-sullivan** [comment]
I think I see what your saying, the double space stays in, but the raw isn't required, I think this stems back to when I was creating it, that I was playing around with using raw, and likely never tried without, still I want to do a test on my end, JUST to make sure, as it has the potential to break things.

**Review by sean-m-sullivan — APPROVED** [review]
Looks good, was able to test, and it works as advertised, would never have 2nd guessed the raw part

**Pull request merged**
