### PR TITLE
Fix credential for project

### LINKED ISSUE #224: Not updating credentials when we create project
When I create a project and mention the credential, everything updates except credentials.

```
controller_projects:
  - name: ansible-playbook-test
    scm_type: git
    scm_url: git@xxxxx:DC/xxxxxxx.git
    scm_branch: inventory-update
    description: Test inventory auto update and workflows
    organization: OPS
    credential: xxxxxx-OPS
    wait: true
    update: true
    scm_clean: 'yes'
    scm_delete_on_update: 'yes'
    scm_update_on_launch: 'yes'
    allow_override: 'yes'
```

@sean-m-sullivan  Could you please help me

### PR DESCRIPTION
**Pull request by Tompage1994**
### What does this PR do?
Made the option for credential in projects as `credential`. Have also allowed (defaulted) the use of `scm_credential` to allow for backwards compatibility.

### How should this be tested?
Have added an example to the CI playbook config

### Is there a relevant Issue open for this?
Provide a link to any open issues that describe the problem you are solving.
resolves #224 

### Other Relevant info, PRs, etc.
Looks like this isn't required for the tower_configuration collection as project remained as `scm_credential`

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
Needs a new line, and for some reason its balking as if there is no default

**Comment by Tompage1994** [comment]
> Needs a new line, and for some reason its balking as if there is no default

Yeah thats my bad. I missed the default function out (Was trying to do it too quickly!) Should be good now

**Comment by Tompage1994** [comment]
Opened #226 to fix the linting pipeline

**Comment by sean-m-sullivan** [comment]
"msg": "Request to 
  /api/v2/credentials/
  ?name= 
  {'credential_type': {'kind': 'scm', 'name': 'Source Control', 'type': 'credential_type'}, 
  'name': 'AWX-Collection-tests-controller_workflow_job_template-scm-cred', 
  'organization': {'name': 'Default', 'type': 'organization'}, 
  'type': 'credential'} 
  returned 0 items, expected 1",

ON export project test

**Comment by Tompage1994** [comment]
Got that fixed now :)

**Review by sean-m-sullivan — APPROVED** [review]
Did not care about the merge/lint knew that would resolve itself, but wanted to the actual test to pass. LGTM

**Pull request merged**
